sylius_twig_hooks:
    hooks:
        'sylius_admin.customer.show.content.sections':
            mailchimp:
                template: '@WebgriffeSyliusMailchimpPlugin/admin/customer/show/sections/mailchimp.html.twig'
                priority: -100
