sylius_twig_hooks:
    hooks:
        'sylius_shop.account.register.content.form':
            mailchimp_newsletter_checkbox:
                template: '@WebgriffeSyliusMailchimp/shop/newsletter/checkbox.html.twig'
                priority: -100

        'sylius_shop.checkout.address.content.form':
            mailchimp_newsletter_checkbox:
                template: '@WebgriffeSyliusMailchimp/shop/newsletter/checkbox.html.twig'
                priority: -100

        'sylius_shop.checkout.complete.content.form':
            mailchimp_newsletter_checkbox:
                template: '@WebgriffeSyliusMailchimp/shop/newsletter/checkbox.html.twig'
                priority: -100

        'sylius_shop.account.profile_update.update.content.main.form':
            mailchimp_newsletter_checkbox:
                template: '@WebgriffeSyliusMailchimp/shop/newsletter/checkbox.html.twig'
                priority: -100
