imports:
    - { resource: "twig_hooks/**/*.yaml" }

monolog:
    handlers:
        mailchimp:
            type: stream
            path: "%kernel.logs_dir%/mailchimp.log"
            level: debug
            channels: [mailchimp]
